const PRODUCTS_ARRAY =  [
  {
    id: 1,
    title: 'Montblanc Meisterstück Doue Geometry Classique Platinum Ballpoint Pen',
    category: 'ballpoint',
    description: 'The Montblanc Meisterstück Doue Geometry Classique platinum midsize ball pen is larger than the standard Classiq.ue but slightly smaller than the large LeGrand. This writing instrument made of black precious resin, engraved with its three-dimensional geometric pattern cap with optical effect in a sophisticated platinum tone, a platinum-coated clip and three platinum-coated rings embossed with the Montblanc brand name. Finished with a mother-of-pearl Montblanc emblem, it appeals to one’s individuality.',
    price: 505, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/13984/48/mbbpp1.png',
  },
  {
    id: 2,
    title: 'Montblanc Meisterstuck Classique Rose Gold Trim Ballpoint Pen',
    category: 'ballpoint',
    description: 'This beautiful Meisterstück Red Gold Classique ballpoint pen is a standout piece from a brand known worldwide for their luxury writing instruments.',
    price: 335, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/4041/48/104770.png',
  },
  {
    id: 3,
    title: 'Montblanc Starwalker Precious Resin Ball Pen',
    category: 'ballpoint',
    description: "This Starwalker ball pen has a deep black resin and striking platinum details which reflects Montblanc's unique style, with a new blue translucent dome beneath the Montblanc emblem.",
    price: 290, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/7605/48/118848-1.png',
  },
  {
    id: 4,
    title: 'Montblanc Meisterstuck Doue Geometry Classique Platinum Fountain Pen',
    category: 'fountain',
    description: 'The Meisterstück Doue Geometry Classique platinum fountain pen is both a timeless classic and a truly modern statement piece from Montblanc.',
    price: 750, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/13996/48/mbfpp1.png',
  },
  {
    id: 5,
    title: 'Montblanc Meisterstück 145 Platinum Trim Fountain Pen',
    category: 'fountain',
    description: 'The Montblanc Meisterstuck 145 black fountain pen features a stunning gold nib and platinum coating, making the ultimate gift for someone special.',
    price: 495, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/1439/48/02-01-01-106522-1509620807.png',
  },
  {
    id: 6,
    title: 'Montblanc Blue Hour LeGrand Solitaire Fountain Pen',
    category: 'fountain',
    description: 'The Montblanc Meisterstück Solitaire Blue Hour Le Grand fountain pen has a hand-crafted Au750 18K gold nib rhodium-coated with a special design and a piston converter.',
    price: 1250, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/14145/48/bhfp1.png',
  },
  {
    id: 7,
    title: 'Montblanc Meisterstück LeGrand Gold Trim Rollerball Pen',
    category: 'rollerball',
    description: 'This iconic Montblanc Meisterstuck LeGrand Black Rollerball Pen has gold trims and is perfect for those seeking a smooth and luxurious writing experience.',
    price: 410, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/4033/48/02-01-01-11402.png',
  },
  {
    id: 8,
    title: 'Cross Bailey Light Glossy Black Rollerball Pen',
    category: 'rollerball',
    description: 'The Cross Bailey Light Glossy rollerball pens have the same high-quality performance and style as the best-selling Bailey metal collection, but now in a light-weight glossy resin!',
    price: 17, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/8226/48/bailey-light-black-rb-full.png',
  },
  {
    id: 9,
    title: 'Cross ATX Brushed Rose Gold PVD Rollerball Pen',
    category: 'rollerball',
    description: 'Cross brings modern industrial design trends to the fore in this chic, urban ATX rose gold PVD rollerball, with a distinct profile and a sweeping clip that wraps around the cap.',
    price: 75, 
    pictureUrl: 'https://www.penshop.co.uk/thumbnails/0/2157/48/111182.png',
  },
]

export default PRODUCTS_ARRAY